### ISSUE TITLE
兄弟 请问你是怎么获取到acfun app的api的 

### ISSUE THREAD

**Issue by mrchenxxx** [gerayking/acfunMobile#1]
我最近也在抓app的api 可惜能力有限 麻烦看到消息后告知一下，不吝赐教！
（我想获取分享视频的api，或者说 怎么才能让python完成自动分享 完成任务呢？）

**Comment by gerayking** [comment]
分享视频有网页端和移动端的，两个接口是不一样的，网页端的是直接用fillder就能爬，移动端的建议逍遥模拟器+fillder爬。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;c834482351&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月4日(星期五) 晚上9:23
收件人:&nbsp;&quot;gerayking/acfunMobile&quot;<acfunMobile@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)

**Comment by mrchenxxx** [comment]
能帮忙 爬一下移动端分享到微信的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gerayking"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 晚上9:35
收件人: "gerayking/acfunMobile"<acfunMobile@noreply.github.com&gt;; 
抄送: "陈晓东"<834482351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)





 分享视频有网页端和移动端的，两个接口是不一样的，网页端的是直接用fillder就能爬，移动端的建议逍遥模拟器+fillder爬。------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;c834482351&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年9月4日(星期五) 晚上9:23 
 收件人:&amp;nbsp;&amp;quot;gerayking/acfunMobile&amp;quot;<acfunMobile@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;Subscribed&amp;quot;<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)

**Comment by gerayking** [comment]
我现在换系统了，不太方便……------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;c834482351&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月4日(星期五) 晚上9:37
收件人:&nbsp;&quot;gerayking/acfunMobile&quot;<acfunMobile@noreply.github.com&gt;;
抄送:&nbsp;&quot;gerayking&quot;<919179287@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)

**Comment by mrchenxxx** [comment]
行吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gerayking"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 晚上9:43
收件人: "gerayking/acfunMobile"<acfunMobile@noreply.github.com&gt;; 
抄送: "陈晓东"<834482351@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)





 我现在换系统了，不太方便……------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;c834482351&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年9月4日(星期五) 晚上9:37 
 收件人:&amp;nbsp;&amp;quot;gerayking/acfunMobile&amp;quot;<acfunMobile@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;gerayking&amp;quot;<919179287@qq.com&amp;gt;;&amp;quot;Comment&amp;quot;<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1) 
&mdash;

**Comment by mrchenxxx** [comment]
你好，我爬取移动端的，配置了证书了，但是打开app就没有网络，怎么解决啊，

**Comment by gerayking** [comment]
没有网络是因为https被拦截了，换安卓5



---原始邮件---
发件人: "c834482351"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 下午2:09
收件人: "gerayking/acfunMobile"<acfunMobile@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"gerayking"<919179287@qq.com&gt;;
主题: Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)




 
你好，我爬取移动端的，配置了证书了，但是打开app就没有网络，怎么解决啊，

**Comment by mrchenxxx** [comment]
安卓模拟器换安卓5吗？在模拟器怎么切换啊？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;gerayking&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月10日(星期四) 下午2:12
收件人:&nbsp;&quot;gerayking/acfunMobile&quot;<acfunMobile@noreply.github.com&gt;;
抄送:&nbsp;&quot;c834482351&quot;<834482351@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)

**Comment by gerayking** [comment]
用逍遥



---原始邮件---
发件人: "c834482351"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 下午2:15
收件人: "gerayking/acfunMobile"<acfunMobile@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"gerayking"<919179287@qq.com&gt;;
主题: Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)




 安卓模拟器换安卓5吗？在模拟器怎么切换啊？------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;gerayking&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年9月10日(星期四) 下午2:12 
 收件人:&amp;nbsp;&amp;quot;gerayking/acfunMobile&amp;quot;<acfunMobile@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;c834482351&amp;quot;<834482351@qq.com&amp;gt;;&amp;quot;Author&amp;quot;<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)

**Comment by mrchenxxx** [comment]
谢谢兄弟，已经成功，原来是卡在我之前用的安卓7了，十分感谢~！

**Comment by gerayking** [comment]
不客气



---原始邮件---
发件人: "c834482351"<notifications@github.com&gt;
发送时间: 2020年9月10日(周四) 晚上7:37
收件人: "gerayking/acfunMobile"<acfunMobile@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"gerayking"<919179287@qq.com&gt;;
主题: Re: [gerayking/acfunMobile] 兄弟 请问你是怎么获取到acfun app的api的  (#1)




 
谢谢兄弟，已经成功，原来是卡在我之前用的安卓7了，十分感谢~！
